### ISSUE TITLE
P1389 [types.basic.primary] Primary types - shouldn't suggest `std::u8string` currently

### ISSUE THREAD

**Issue by YehezkelShB** [cjdb/wg21#6]
P1389 [[types.basic.primary]](https://github.com/cjdb/wg21/blob/master/sg20/d1389/d1389.bs#L144) suggests using `std::u8string` type as the default string type presented to beginners.
This is wrong, in my opinion, as this type is missing basic usability as of C++20, because there are no stream facilities for reading/writing this type and even no tools to convert it to `char`/`wchar_t` (the only types that has support in `iostream` today).

**Comment by cjdb** [comment]
Yes, I agree. Even {fmt} doesn't `print` `u8string` ☹️ Can you please make this a formal proposal and we'll discuss it in Cologne?

**Comment by YehezkelShB** [comment]
Isn't this just like a DR, not full proposal?
OK, I hope to get to it soon.

**Comment by YehezkelShB** [comment]
@cjdb 
Would you please have the time to take a look if this is the correct format to do it?
https://github.com/YehezkelShB/cpp_proposals/pull/2
Thanks in advance!

**Comment by YehezkelShB** [comment]
Closing this as it'll be proposed with the paper linked above.
